[package]
name = "localization-macros"
version = "0.1.2"
edition = "2021"
description = "t! macro, the easiest way."
license = "MIT"
documentation = "https://docs.rs/localization-macros"
repository = "https://github.com/neodyland/localization"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"
proc-macro2 = "1.0.66"
quote = "1.0.33"
serde = "1.0.188"
serde_json = "1.0.105"
syn = "2.0.31"

[lib]
proc-macro = true
